### ISSUE TITLE
Is there an option that input can start with zero?

### ISSUE THREAD

**Issue by bmm522** [jongmin4943/vue3-directive-number#2]
When I'm using that library and if the first number is 0, the zeros disappear. 🤔
Is there an option to control this?
If it doesn't have that option, it would be nice to add it.

**Comment by jongmin4943** [comment]
It is designed for only number at the beginning.
Since it allows `comma` already, allowing only numbers doesn't really make sense any more.
I think it's a good idea to have that feature. 
Would you be willing to help implement this feature?

**Comment by bmm522** [comment]
Okay, I'll try
